### ISSUE TITLE
[Feature] Brew Formula

### ISSUE THREAD

**Issue by ZPascal** [dueckminor/go-sshtunnel#55]
Hi @dueckminor, I would prefer the Brew Formula for the ARM and Intel based MACs to be consumed directly by a package management system. What do you think?

**Comment by dueckminor** [comment]
Are you using the `sshtunnel` directly from your Mac? I have not expected, that this is already a use case.

**Comment by ZPascal** [comment]
Yes, I'm using the binary especially the Socks5 Proxy functionality from my mac.

**Comment by ZPascal** [comment]
I would prepare a [Goreleaser](https://goreleaser.com/intro/) configuration and would setup/ adjust the GH workflow to handle the new release option. Should I prepare a PR to set up the release option?

**Comment by dueckminor** [comment]
Feel free to contribute
